apiVersion: v1
kind: Pod
metadata:
  name: flask-app
spec:
  containers:
  - name: flask-container
    image: docker.io/milanroat/my-Flaskimage
    ports:
    - containerPort: 5000
    restartPolicy: Always